# Generated by Django 5.1.6 on 2025-02-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_cars_product_available_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='available',
        ),
    ]
