# Generated by Django 5.1.6 on 2025-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_remove_cars_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
