# Generated by Django 5.1.6 on 2025-02-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_cars_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='available',
            new_name='available1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='color',
            new_name='color1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='price',
            new_name='price1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='stock',
            new_name='stock1',
        ),
    ]
