# Generated by Django 5.1.6 on 2025-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_rename_available_cars_available1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='cars',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
