# Generated by Django 5.1.6 on 2025-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0006_car_delete_cars_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_image/'),
        ),
    ]
